/**
 * S, the single mutable game state (phase machine, timers, springs, camera, lights). window.APP is the test and
 * debug hook object; see CLAUDE.md.
 */
export const S = {
  phase: 'entering',
  t: 0,
  rt: 0,
  ts: 1,
  slowmo: 0,
  charge: 0,
  holding: false,
  auto: false,
  downAt: 0,
  reached: [0, 0, 0, 0],
  tease: 0,
  teaseKey: 's',
  beat: 0,
  r: -1,
  vr: -1,
  spec: null,
  fake: false,
  upgrading: false,
  up: 0,
  force: -1,
  seed: 1,
  backOn: true,
  pos: {
    x: 0,
    y: 0,
    vy: 0,
  },
  landed: false,
  sq: {
    x: 0,
    v: 0,
  },
  spin: {
    a: 0,
    from: 0,
    to: 0,
    t: 1,
    dur: 1,
  },
  pulse: 0,
  tilt: {
    x: 0,
    y: 0,
  },
  ptr: {
    nx: 0,
    ny: 0,
    last: -9,
  },
  trauma: 0,
  flash: 0,
  flashKey: 'w',
  rays: 0,
  raysT: 0,
  rayAng: 0,
  glow: 0,
  box: 0,
  zoom: {
    x: 1,
    v: 0,
  },
  amb: 0.3,
  cardI: 0.5,
  cardIT: 0.5,
  lightKey: 's',
  beam: 0,
  torchBoost: 0,
  hitstop: 0,
  hitstopDur: 1,
  after: -1,
  stat: {
    done: true,
  },
  bars: [0, 0, 0],
  barT: [0, 0, 0],
  barFlash: [0, 0, 0],
  barDone: [1, 1, 1],
  title: null,
  stamp: null,
  glitch: 0,
  hidden: false,
  col: null,
  pending: null,
  zapAcc: 0,
  suckAcc: 0,
  sparkAcc: 0,
  flameAcc: 0,
  ca: 0,
  chains: [true, true, true, true],
  lockOn: true,
  wall: {
    active: false,
    rebuild: false,
    t: 0,
    rt: 0,
    r: 0,
  },
  summon: 0,
  summonChime: false,
  popT0: -9,
  crk: 0,
  artStars: [],
  cx: 0,
  cy: 0,
  colScale: 1,
};
window.APP = {
  S,
};
export const tens = () => (S.phase === 'idle' ? S.charge : S.phase === 'upgrading' ? S.up : 0);
